/**
 * Liceman Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CourseSearchResult { 
    title?: string;
    headline?: string;
    imageURL?: string;
    courseId?: string;
    instructor?: string;
    rating?: string;
    reviewQuantity?: string;
    content_info_duration?: string;
    content_info_lectures?: string;
}

