/**
 * Liceman Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurriculumClasses } from './curriculumClasses';


export interface CurriculumSection { 
    title?: string;
    summary?: string;
    curriculumClasses?: Array<CurriculumClasses>;
}

