/**
 * Liceman Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrainingCreationRequestDTO { 
    area?: TrainingCreationRequestDTO.AreaEnum;
    title?: string;
    comment?: string;
}
export namespace TrainingCreationRequestDTO {
    export type AreaEnum = 'BACKEND' | 'FRONTEND' | 'DEVOPS' | 'DATA' | 'SALESFORCE';
    export const AreaEnum = {
        Backend: 'BACKEND' as AreaEnum,
        Frontend: 'FRONTEND' as AreaEnum,
        Devops: 'DEVOPS' as AreaEnum,
        Data: 'DATA' as AreaEnum,
        Salesforce: 'SALESFORCE' as AreaEnum
    };
}


