/**
 * Liceman Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateTrainingByAdminDTO { 
    status?: UpdateTrainingByAdminDTO.StatusEnum;
}
export namespace UpdateTrainingByAdminDTO {
    export type StatusEnum = 'PENDING_MENTOR' | 'PENDING_USER' | 'PENDING_ADMIN' | 'APPROVED' | 'REJECTED' | 'FINISHED';
    export const StatusEnum = {
        PendingMentor: 'PENDING_MENTOR' as StatusEnum,
        PendingUser: 'PENDING_USER' as StatusEnum,
        PendingAdmin: 'PENDING_ADMIN' as StatusEnum,
        Approved: 'APPROVED' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum,
        Finished: 'FINISHED' as StatusEnum
    };
}


