/**
 * Liceman Documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserRequestDTO { 
    firstname?: string;
    lastname?: string;
    email?: string;
    password?: string;
    role?: UserRequestDTO.RoleEnum;
    area?: UserRequestDTO.AreaEnum;
    phone?: string;
    hasTeams?: boolean;
}
export namespace UserRequestDTO {
    export type RoleEnum = 'USER' | 'ADMIN' | 'MENTOR';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Mentor: 'MENTOR' as RoleEnum
    };
    export type AreaEnum = 'BACKEND' | 'FRONTEND' | 'DEVOPS' | 'DATA' | 'SALESFORCE';
    export const AreaEnum = {
        Backend: 'BACKEND' as AreaEnum,
        Frontend: 'FRONTEND' as AreaEnum,
        Devops: 'DEVOPS' as AreaEnum,
        Data: 'DATA' as AreaEnum,
        Salesforce: 'SALESFORCE' as AreaEnum
    };
}


